### ISSUE TITLE
Runs on localhost but not when you set the host to an IP

### ISSUE THREAD

**Issue by GerritKuilder** [psborul/nuxt-chat-app#20]
Have been struggling with this and found a lot of references to possible solution but nothing worked.

I develop mainly on an external machine and my apps run under an IP number and port.

the site comes up nicely and as expected but the websocket part came up with errors.
websocket.js?0882:120 WebSocket connection to 'ws://192.168.2.100:5000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
===

After a lot of checking and also trying other samples with socket IO I installed this chat app on my local machine.

Lo and behold, it worked...

I have shut down my nginx server and the issue still persists (found a lot of references to that, but that only listens to 80 and 443

Any advice?

Kind Regards,

Gerrit Kuilder

**Comment by GerritKuilder** [comment]
see https://socket.io/blog/socket-io-2-4-0/

io.origins((_, callback) => {
  callback(null, true);
});

solved it for me

**Comment by psborul** [comment]
@GerritKuilder Thank you for your attention and solution of your problem
