### ISSUE TITLE
i keep getting errors with layouts/index.js. Syntax errors even though I copied the code the exact same

### ISSUE THREAD

**Issue by DogsAreTheShit** [psborul/nuxt-chat-app#4]
![Screen Shot 2020-06-03 at 12 03 24 AM](https://user-images.githubusercontent.com/65428292/83594608-a810b500-a52d-11ea-853b-b14d3497b541.png)

**Comment by psborul** [comment]
Hi, thanks for the care
Do you have an actual master branch?

**Comment by DogsAreTheShit** [comment]
Yup that was the issue. Thanks! :D
